export const COUNTRY_DETAILS_REQUESTING = "COUNTRY_DETAILS_REQUESTING";
export const COUNTRY_DETAILS = "COUNTRY_DETAILS";
export const COUNTRY_DETAILS_UNKNOWN = "COUNTRY_DETAILS_UNKNOWN";
export const REGION_LISTS = "REGION_LISTS";